all: 8_1 8_3

8_1: main_8_1.cpp FibonacciRange.cpp FibonacciIterator.cpp
	g++ -o 8_1.out main_8_1.cpp FibonacciRange.cpp FibonacciIterator.cpp -I.

8_3: main_8_3.cpp PrimeNumberRange.cpp FibonacciRange.cpp FibonacciIterator.cpp
	g++ -o 8_3.out main_8_3.cpp PrimeNumberRange.cpp FibonacciRange.cpp FibonacciIterator.cpp -I.

clean:
	rm ./8_*.out